project_id = "kmunvgkwmdonygmldhgf"

[functions.manage-users]
verify_jwt = false

[functions.manage-permissions]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.dispatch-carga]
verify_jwt = false

[functions.carga-callback]
verify_jwt = false